name: Rust

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]

env:
  CARGO_TERM_COLOR: always
  CUBISM_CORE: third-party

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Clang
    uses: egor-tensin/setup-clang@v1
    with:
      version: latest
      platform: x64
    - name: Build #设置环境变量并构建
      run: |
        $env:CUBISM_CORE="third-party"
        ls env:
        cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Check
      run: |
        echo 进入构建目录
        cd target
        echo 查看
        tree
    #上传全部内容
    - uses: actions/upload-artifact@v2 
      with:
        name: libgodot_cubism.so
        path: target/debug
  
